example_key: ENC[AES256_GCM,data:P81rtmpiO48jL3Fwng==,iv:BBm6mz25HfEkQRffJ8HaaDhBLMGhfO38XAekw9y69gc=,tag:7HtVx1AuDlnWdTN+v56PJg==,type:str]
#ENC[AES256_GCM,data:8UdvWj6S15UhjZUXbeO3Lw==,iv:rXJytEK1wSudGw2M5LtyUNPtCcvNR9SrvVQIxZzflFc=,tag:fVtsd0O8Ti8LQc6QlWdi4g==,type:comment]
example_array:
    - ENC[AES256_GCM,data:cH9I9ydkzLvxBiz69yg=,iv:mV7W4h3YhE5q5UQ5Qh6n0mbPfmnDPx/z+4M354DIwAw=,tag:RRHbBLVmt5qncPy738XMjw==,type:str]
    - ENC[AES256_GCM,data:wEwEIky1glJg/KJslQA=,iv:sWJ/YvBRMYa7rFpYWhYn+YcKTD21RqIIdgN5DudiCOY=,tag:585jhCDKyiSO8yD2PeIofA==,type:str]
example_number: ENC[AES256_GCM,data:32+MB7HDi3nUcw==,iv:tznu3UyVobZsOKK0PvjGLkCnoF/yqk0I8V6fKxwiDWo=,tag:rN4re8dXvi/ymGeYysTMbg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:c6I7rw==,iv:uCwumAGbkjEjplIOdMDBVE8M881+aQDH93Yd6jPHozo=,tag:LEIRX+t9myNbm5Q0FiButA==,type:bool]
    - ENC[AES256_GCM,data:c8M5wcg=,iv:9yYBCE2AfhToDTTbjKehLwGNhGUnC7wQFguk2+6IaUg=,tag:n+39StxDz/atQNJChft4ZA==,type:bool]
sops:
    age:
        - recipient: age1eu7mf5gkqdqemvkuaq93fwwy67dkqu3vc6mpyjtf7stz3n3h4eks5p94x5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQW1xdG9qb3lacVV1VmdS
            RUpjTDV4ditKeVFnQkxOVWxhNlUvN0czQVFvCkRUeWFXNVBZYkl5N0t5a2Jyd3lE
            MVBQT0k5ZnBjcnhCdm1ZK0taanNkekEKLS0tIGNBUGdoOXY3bGJpSm13QlMxdW1a
            SjlHTjdITGJBM3ZkVU1NVHNBRmE5azgKYCR/jHaUaGg/NjPaTCcFfimxtuNCz3uz
            87Y4vVQgxVONAdv1AAkOn8cXotN+ifLvGRMzRb/RlLDBM8QFa67OUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18jfep2kqy2cfg003perzgye3ven02ze06nlhmegs6rddluye43nq57sx03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK1ZxL2VkY1dYUlQwNnMz
            aHBuWWpyMlZzQ29tdDZBT0orMzA5RzVRZmtnCkloNC9UZVdLQWo3YWlNOWJ6YWdB
            bjVRdk1SRFpxRGYrK29qZ2V0Uy9RakUKLS0tIFkyT2tHZDY2OGZPQU83QlhDNEEx
            Qlg0WlNwVUdRZ3lpd2tsVVRQcjZkRXMK3uSQSOHLQk9aFJ2hFtA+OioBh6HRcOz0
            VovP+DjM2CQBz7ODIzEch3IsY8yc0yFAVSz/vmAUQV9HfWWzzh5KFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T08:45:01Z"
    mac: ENC[AES256_GCM,data:tHByu9ceILZ0npWxAQF3t82Z4LUxv5tTGl8wQSLTN3vgM1I70yydFAMqTqNkNVIIjMXsV1kB8XPmLoGhk9vK2s703F5JqCk+bAH7cKVZQEIGvXIjYSVFG+ytcuQotzK3yVew3qKh62rohmoBf4kK1J8pFlZztacOMqnlT73EtN8=,iv:36r1KmfYfXG8jeGvuswPZ/VvKlsQ6jyiXLr8D3yqjlU=,tag:8ByI5eWQULxg2wjA7Cfb8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
