keys:
  # desktops
  - &interstellar age1eu7mf5gkqdqemvkuaq93fwwy67dkqu3vc6mpyjtf7stz3n3h4eks5p94x5
  - &john age1gl7yg0sfv3rpxjw90xtq3y5hm462cnfm77y25hregrsudchpy92s548mjs

  # servers
  - &nanorion age1x0dcfhnxfzt3dnykg7f7erj5m2l6maqtwje5scd5e27uyka7pawq36gl32
creation_rules:
  - path_regex: secrets/interstellar\.yaml$
    key_groups:
      - age:
        - *interstellar

  - path_regex: secrets/john\.yaml$
    key_groups:
      - age:
        - *john

  - path_regex: secrets/nanorion\.yaml$
    key_groups:
      - age:
        - *interstellar
        - *john
        - *nanorion
